Improve upgrade script

diff --git a/scripts/install b/scripts/install
--- a/scripts/install
+++ b/scripts/install
@@ -17,66 +17,28 @@
 # You should have received a copy of the GNU Affero General Public License
 # along with this program.  If not, see <http://www.gnu.org/licenses/>.
 
+# This is an upgrade?
+upgrade=$([ "$VPNCLIENT_UPGRADE" == 1 ] && echo true || echo false)
+
 # Retrieve arguments
 domain=${1}
 url_path=${2}
 server_name=${3}
 
-##
-## These arguments are optional but YunoHost is not yet able to handle them with the web installer
-## See manifest.json.options
-##
-#
-#crt_client_path=${4}
-#crt_client_key_path=${5}
-#crt_server_ca_path=${6}
-#login_user=${7}
-#login_passphrase=${8}
+if ! $upgrade; then
 
-# Check arguments
-if [ -z "${server_name}" ]; then
-  echo "ERROR: You need a VPN server name" >&2
-  exit 1
-fi
+  # Check arguments
+  if [ -z "${server_name}" ]; then
+    echo "ERROR: You need a VPN server name" >&2
+    exit 1
+  fi
+  
+  # Check domain/path availability
+  sudo yunohost app checkurl ${domain}${url_path} -a vpnclient
+  if [ ! $? -eq 0 ]; then
+    exit 1
+  fi
 
-#if [ \( -z "${crt_client_path}" -a ! -z "${crt_client_key_path}" \)\
-#    -o \( ! -z "${crt_client_path}" -a -z "${crt_client_key_path}" \) ]; then
-#
-#  echo "ERROR: A client certificate is needed when you suggest a key (or vice versa)" >&2
-#  exit 1
-#fi
-#
-#if [ ! -z "${crt_client_key_path}" -a -z "${crt_server_ca_path}" ]; then
-#  echo "ERROR: If you can suggest a local path for the client certificates, you probably can suggest one other for the (mandatory) CA server" >&2
-#  exit 1
-#fi
-#
-#if [ \( -z "${login_user}" -a ! -z "${login_passphrase}" \)\
-#    -o \( ! -z "${login_user}" -a -z "${login_passphrase}" \) ]; then
-#
-#  echo "ERROR: A login password is needed when you suggest a login user (or vice versa)" >&2
-#  exit 1
-#fi
-#
-#if [ ! -z "${crt_client_path}" -a ! -f "${crt_client_path}" ]; then
-#  echo "ERROR: The local path <${crt_client_path}> does not exist" >&2
-#  exit 1
-#fi
-#
-#if [ ! -z "${crt_client_key_path}" -a ! -f "${crt_client_key_path}" ]; then
-#  echo "ERROR: The local path <${crt_client_key_path}> does not exist" >&2
-#  exit 1
-#fi
-#
-#if [ ! -z "${crt_server_ca_path}" -a ! -f "${crt_server_ca_path}" ]; then
-#  echo "ERROR: The local path <${crt_server_ca_path}> does not exist" >&2
-#  exit 1
-#fi
-
-# Check domain/path availability
-sudo yunohost app checkurl ${domain}${url_path} -a vpnclient
-if [ ! $? -eq 0 ]; then
-  exit 1
 fi
 
 # Install packages
@@ -90,15 +52,19 @@ if [ $? -ne 0 ]; then
   sudo apt-get --assume-yes --force-yes install ${packages}
 fi
 
-# Save arguments
-sudo yunohost app setting vpnclient service_enabled -v 1
-sudo yunohost app setting vpnclient server_name -v "${server_name}"
-sudo yunohost app setting vpnclient server_port -v 1194
-sudo yunohost app setting vpnclient server_proto -v udp
-sudo yunohost app setting vpnclient ip6_addr -v none
-sudo yunohost app setting vpnclient ip6_net -v none
-sudo yunohost app setting vpnclient login_user -v "${login_user}"
-sudo yunohost app setting vpnclient login_passphrase -v "${login_passphrase}"
+if ! $upgrade; then
+
+  # Save arguments
+  sudo yunohost app setting vpnclient service_enabled -v 1
+  sudo yunohost app setting vpnclient server_name -v "${server_name}"
+  sudo yunohost app setting vpnclient server_port -v 1194
+  sudo yunohost app setting vpnclient server_proto -v udp
+  sudo yunohost app setting vpnclient ip6_addr -v none
+  sudo yunohost app setting vpnclient ip6_net -v none
+  sudo yunohost app setting vpnclient login_user -v "${login_user}"
+  sudo yunohost app setting vpnclient login_passphrase -v "${login_passphrase}"
+
+fi
 
 # Install IPv6 scripts
 sudo install -o root -g root -m 0755 ../conf/ipv6_expanded /usr/local/bin/
@@ -125,26 +91,6 @@ sudo find /var/www/vpnadmin/ -type d -exec chmod +x {} \;
 # Copy certificates
 sudo mkdir -pm 0770 /etc/openvpn/keys/
 sudo chown root:admins /etc/openvpn/keys/
-
-#[ ! -z "${crt_client_path}" ] &&\
-#  sudo install -b -o root -g admins -m 0660 "${crt_client_path}" /etc/openvpn/keys/user.crt
-#
-#[ ! -z "${crt_client_key_path}" ] &&\
-#  sudo install -b -o root -g admins -m 0660 "${crt_client_key_path}" /etc/openvpn/keys/user.key
-#
-#[ ! -z "${crt_server_ca_path}" ] &&\
-#  sudo install -b -o root -g admins -m 0660 "${crt_server_ca_path}" /etc/openvpn/keys/ca-server.crt
-#
-#sudo rm -f "${crt_client_path}" "${crt_client_key_path}" "${crt_server_ca_path}"
-
-# Credentials file for (optional) login
-#sudo cat << EOF > /etc/openvpn/keys/credentials
-#${login_user}
-#${login_passphrase}
-#EOF
-#
-#sudo chown -R root:admins /etc/openvpn/keys/credentials
-#sudo chmod 0460 /etc/openvpn/keys/credentials
 
 # Fix confs
 ## nginx
@@ -177,25 +123,22 @@ sudo systemctl restart php5-fpm
 sudo systemctl reload nginx
 
 sudo systemctl enable ynh-vpnclient
-sudo systemctl start ynh-vpnclient
 
-# Update SSO for vpnadmin
-sudo yunohost app ssowatconf
+if ! $upgrade; then
+  sudo systemctl start ynh-vpnclient
 
-# Restart hotspot service if installed (and started) to change NAT configuration (now on tun0)
-# A new start will fix the interface without unsetting all stuff
-#if [ -e /tmp/.ynh-hotspot-started ]; then
-#  sudo ynh-hotspot start
-#fi
+  sudo yunohost service add ynh-vpnclient
+  sudo yunohost app ssowatconf
 
-# Check configuration consistency
-
-if [ -z "${crt_server_ca_path}" ]; then
-  echo "WARNING: VPN Client is not started because you need to define a server CA through the web admin" >&2
-fi
-
-if [ -z "${crt_client_key_path}" -a -z "${login_user}" ]; then
-  echo "WARNING: VPN Client is not started because you need either a client certificate, either a username (or both)" >&2
+  # Check configuration consistency
+  
+  if [ -z "${crt_server_ca_path}" ]; then
+    echo "WARNING: VPN Client is not started because you need to define a server CA through the web admin" >&2
+  fi
+  
+  if [ -z "${crt_client_key_path}" -a -z "${login_user}" ]; then
+    echo "WARNING: VPN Client is not started because you need either a client certificate, either a username (or both)" >&2
+  fi
 fi
 
 exit 0
