replace iptables rules in openvpn scripts with nft rules

diff --git a/conf/scripts/route-down.d/10-vpnclient-unset-firewall b/conf/scripts/route-down.d/10-vpnclient-unset-firewall
--- a/conf/scripts/route-down.d/10-vpnclient-unset-firewall
+++ b/conf/scripts/route-down.d/10-vpnclient-unset-firewall
@@ -1,41 +1,38 @@
 #!/bin/bash
 
 is_firewall_set() {
-  ip6tables -w -nvL OUTPUT | grep vpnclient_out | grep -q "${wired_device}" \
-  && iptables -w -nvL OUTPUT | grep vpnclient_out | grep -q "${wired_device}"
+  nft list chain inet filter output | grep vpnclient_out | grep -q "${wired_device}"
 }
 
-wired_device=$(ip route | awk '/default via/ { print $5; }')
+delete_nft_rule() {
+  local chain=$1
+  shift
+  local rule=$@
+
+  handle=$(nft -a list chain inet filter "${chain}" | sed -E 's/\s*counter packets [0-9]+ bytes [0-9]+\s*/ /g' | grep "${rule}" | grep -Po 'handle \K\d+')
+  if [[ -n "${handle}" ]]; then
+    nft delete rule inet filter "${chain}" handle "$handle"
+  else
+    >&2 echo "Cannot remove rule in chain ${chain}: ${rule} doesn't exist"
+    return 1
+  fi
+}
+
+wired_device=$(ip route | awk '/default via/ { print $5; exit; }')
 
 rm -f /etc/yunohost/hooks.d/post_iptable_rules/90-vpnclient
 if is_firewall_set; then  
-  # IPv4
+  delete_nft_rule "input" "iifname \"${wired_device}\" jump vpnclient_in"
+  delete_nft_rule "output" "iifname \"${wired_device}\" jump vpnclient_out"
+  delete_nft_rule "forward" "iifname \"${wired_device}\" jump vpnclient_fwd"
 
-  iptables -w -D INPUT -i "${wired_device}" -j vpnclient_in
-  iptables -w -D OUTPUT -o "${wired_device}" -j vpnclient_out
-  iptables -w -D FORWARD -o "${wired_device}" -j vpnclient_fwd
+  nft flush chain inet filter vpnclient_in
+  nft flush chain inet filter vpnclient_out
+  nft flush chain inet filter vpnclient_fwd
 
-  iptables -w -F vpnclient_in
-  iptables -w -F vpnclient_out
-  iptables -w -F vpnclient_fwd
-
-  iptables -w -X vpnclient_in
-  iptables -w -X vpnclient_out
-  iptables -w -X vpnclient_fwd
-
-  # IPv6
-  
-  ip6tables -w -D INPUT -i "${wired_device}" -j vpnclient_in
-  ip6tables -w -D OUTPUT -o "${wired_device}" -j vpnclient_out
-  ip6tables -w -D FORWARD -o "${wired_device}" -j vpnclient_fwd
-
-  ip6tables -w -F vpnclient_in
-  ip6tables -w -F vpnclient_out
-  ip6tables -w -F vpnclient_fwd
-
-  ip6tables -w -X vpnclient_in
-  ip6tables -w -X vpnclient_out
-  ip6tables -w -X vpnclient_fwd
+  nft delete chain inet filter vpnclient_in
+  nft delete chain inet filter vpnclient_out
+  nft delete chain inet filter vpnclient_fwd
 
   if ! is_firewall_set; then
     echo "[ OK ] Firewall rules correctly unset"
