replace [ERROR] with [FAIL]

diff --git a/conf/scripts/route-up.d/10-set-firewall b/conf/scripts/route-up.d/10-set-firewall
--- a/conf/scripts/route-up.d/10-set-firewall
+++ b/conf/scripts/route-up.d/10-set-firewall
@@ -15,6 +15,6 @@ fi
 if is_firewall_set; then
   echo "[ OK ] IPv6/IPv4 firewall set"
 else
-  echo "[ERROR] No IPv6/IPv4 firewall set" >&2
+  echo "[FAIL] No IPv6/IPv4 firewall set" >&2
   exit 1
 fi
diff --git a/conf/scripts/route-up.d/20-set-dns b/conf/scripts/route-up.d/20-set-dns
--- a/conf/scripts/route-up.d/20-set-dns
+++ b/conf/scripts/route-up.d/20-set-dns
@@ -30,6 +30,6 @@ fi
 if is_dns_set; then
   echo "[ OK ] Host DNS correctly set"
 else
-  echo "[ERROR] No host DNS set" >&2
+  echo "[FAIL] No host DNS set" >&2
   exit 1
 fi
diff --git a/conf/scripts/route-up.d/30-set-server-ipv6-route b/conf/scripts/route-up.d/30-set-server-ipv6-route
--- a/conf/scripts/route-up.d/30-set-server-ipv6-route
+++ b/conf/scripts/route-up.d/30-set-server-ipv6-route
@@ -77,7 +77,7 @@ if has_nativeip6; then
   if is_serverip6route_set "${new_server_ip6}"; then
     echo "[ OK ] IPv6 server route correctly set"
   else
-    echo "[ERROR] No IPv6 server route set" >&2
+    echo "[FAIL] No IPv6 server route set" >&2
     exit 1
   fi
 else
diff --git a/conf/scripts/route-up.d/40-set-ipv6 b/conf/scripts/route-up.d/40-set-ipv6
--- a/conf/scripts/route-up.d/40-set-ipv6
+++ b/conf/scripts/route-up.d/40-set-ipv6
@@ -17,7 +17,7 @@ if [[ -n "${ip6_addr}" ]] && [[ "${ip6_addr}" != none ]]; then
   if is_ip6addr_set "${ip6_addr}"; then
     echo "[ OK ] IPv6 address correctly set"
   else
-    echo "[ERROR] No IPv6 address set" >&2
+    echo "[FAIL] No IPv6 address set" >&2
     exit 1
   fi
 else
