create openvpn hooks for handling server ipv6 route, dns and firewall rules

diff --git a/conf/scripts/route-up.d/20-set-ipv6 b/conf/scripts/route-up.d/20-set-ipv6
--- a/conf/scripts/route-up.d/20-set-ipv6
+++ b/conf/scripts/route-up.d/20-set-ipv6
@@ -6,6 +6,20 @@ is_ip6addr_set() {
 }
 
 ip6_addr=$(yunohost app setting "vpnclient" "ip6_addr")
-if [[ -n "${ip6_addr}" ]] && [[ "${ip6_addr}" != none ]] && ! is_ip6addr_set "${ip6_addr}"; then
-  ip address add "${ip6_addr}/64" dev tun0
+if [[ -n "${ip6_addr}" ]] && [[ "${ip6_addr}" != none ]];
+  if ! is_ip6addr_set "${ip6_addr}"; then
+    ip address add "${ip6_addr}/64" dev tun0
+  fi
+
+  echo "[INFO] IPv6 delegated prefix found"
+  echo "[INFO] IPv6 address computed from the delegated prefix: ${ip6_addr}"
+
+  if is_ip6addr_set "${ip6_addr}"; then
+    echo "[ OK ] IPv6 address correctly set"
+  else
+    echo "[ERROR] No IPv6 address set" >&2
+    exit 1
+  fi
+else
+  echo "[INFO] No IPv6 delegated prefix found"
 fi
